Repository awslabs/aws-serverless-data-lake-framework, pull requests merged in 2020-11, with the labels that each got.

#6 Approval rule master
  sdlf-cicd/template-cicd-team-repos.yaml
  sdlf-team/scripts/bootstrap_team.sh
  sdlf-team/scripts/template-team-repos.yaml
Labels: enhancement

#10 Major Bug Fix - Kibana SetupCognito Lambda requires KMS permissions
  sdlf-foundations/nested-stacks/template-kibana.yaml
Labels: bug

#12 Dev
  sdlf-team/nested-stacks/template-cicd.yaml
  sdlf-team/nested-stacks/template-kms.yaml
  sdlf-team/scripts/bootstrap_team.sh
  sdlf-team/scripts/template-team-repos.yaml
Labels: bug, enhancement
